@startuml
'https://plantuml.com/class-diagram

class Body {
- position : Vector
- velocity : Vector
- mass : double
+ move (f:Vector,dt:double)
+ forceForm (b : Body) : Vector
+ toString()
}

class Univers_2 {
- numBodies : int
- radius : double
+ Universe (fname : String)
+ Universe (numBodies : int)
+ update (dt : double)
}

class NBodySimulator {
- timeStep : double
- pauseTime : int
- trace : boolean
- numBody : int
+ NBodySimulator(String fname : String, dt:double, pauseTime : int, do_trace: boolean)
+ NBodySimulator(numBodies : int)
+ drawUniverse()
+ simulate (initTime : double, endTime : double, trace : boolean)
+ simulate()
- createCanvas()
+ main (args : String[])
}

Univers_2 *-> "1..*" Body : bodies
NBodySimulator *-> "1" Univers_2

class Vector {
- n : int
- data : double[n]
+ Vector (n : int)
+ Vector (data : double[])
+ length() : int
+ magnitude() : double
+ cartesian (i : int) : double
+ direction() : Vector
+ plus (v : Vector) : Vector
+ minus (v : Vector) : Vector
+ scale (factor : double) : Vector
+ discanceTo (v : Vector) : double
+ dot (v : Vector) : double
+ toString() : String
}

note left of NBodySimulator
//...
nbody = new NBodySimulator(fname,dt,pauseTime,do_trace);
nbody.simylate();

end note


@enduml